default:
  image: python:3.7-buster

stages:
  - validate
  - build

build:
  stage: build
  script:
    - pip install pipenv
    - pipenv install
    - pipenv run pelican -o output -d content
  only:
    - master
    - merge_requests

merge:
  stage: validate
  script:
    - pip install pipenv
    - pipenv install
    - pipenv run python util/validate-tei.py
  only:
    - master
    - merge_requests
