default:
  image: python:3.7-buster

include:
  template: Dependency-Scanning.gitlab-ci.yml

stages:
  - validate
  - build

#dependency_scanning:
#  stage: validate
#  only:
#    - master
#  variables:
#    DS_DISABLE_DIND: "true"
#    DS_PYTHON_VERSION: "3.6"

build:
  stage: build
  script:
    - pip install poetry
    - poetry install --no-dev
    - poetry run pelican -s publishconf.py -o output -d content
  only:
    - master
    - merge_requests

validate:
  stage: validate
  script:
    - pip install poetry
    - poetry install --no-dev
    - poetry run python util/validate-tei.py
  only:
    - merge_requests
