default:
  image: python:3.7-buster

stages:
  - validate
  - build

build:
  stage: build
  script:
    - pip install poetry
    - poetry install --no-dev
    - poetry run pelican -s publishconf.py -o output -d content
  only:
    - default
    - merge_requests

validate:
  stage: validate
  script:
    - pip install poetry
    - poetry install --no-dev
    - poetry run python util/validate-tei.py
  only:
    - merge_requests
