default:
  image: python:3.11-buster

stages:
  - test
  - build
  - deploy

validate:
  stage: test
  script:
    - pip install hatch
    - hatch run default:python util/validate-tei.py
  only:
    - merge_requests
    - uedition-transfer

test-build:
  stage: test
  script:
    - pip install hatch
    - hatch run default:build
  only:
    - merge_requests
    - uedition-transfer

build-and-deploy:
  stage: deploy
  script:
    - pip install hatch
    - poetry install --only main
    - hatch run default:build
    - apt-get update
    - apt-get install -y lftp
    - lftp -e "set ssl:verify-certificate no; mirror -R content/_build/html . ; quit" -u "$FTP_USERNAME,$FTP_PASSWORD" "$FTP_SERVER"
  only:
    - default
