default:
  image: python:3.7-buster

stages:
  - test
  - build
  - deploy

validate:
  stage: test
  script:
    - pip install poetry
    - poetry install --no-dev
    - poetry run python util/validate-tei.py
  only:
    - merge_requests

test-build:
  stage: test
  script:
    - pip install poetry
    - poetry install --no-dev
    - poetry run pelican -s publishconf.py -o output -d content
  only:
    - merge_requests

build-and-deploy:
  stage: deploy
  script:
    - pip install poetry
    - poetry install --only main
    - poetry run pelican -s publishconf.py -o output -d content
    - apt-get update
    - apt-get install -y lftp
    - ls -l
    - echo "$FTPSERVER"
    - echo "$FTPUSERNAME"
    - echo "$FTPPASSWORD"
    - lftp -e "set ssl:verify-certificate no; mirror -R output . ; quit" -u "$FTPUSERNAME,$FTPPASSWORD" "$FTPSERVER"
  only:
    - default
