default:
  image: python:3.10-buster

stages:
  - test
  - build
  - deploy

validate:
  stage: test
  script:
    - pip install poetry
    - hatch run default:python util/validate-tei.py
  only:
    - merge_requests
    - uedition-transfer

test-build:
  stage: test
  script:
    - pip install hatch
    - hatch run default:build
  only:
    - merge_requests
    - uedition-transfer

build-and-deploy:
  stage: deploy
  script:
    - pip install poetry
    - poetry install --only main
    - poetry run pelican -s publishconf.py -o output -d content
    - apt-get update
    - apt-get install -y lftp
    - lftp -e "set ssl:verify-certificate no; mirror -R output . ; quit" -u "$FTP_USERNAME,$FTP_PASSWORD" "$FTP_SERVER"
  only:
    - default
