[tool.poetry]
name = "digitale-gesamtausgabe"
version = "0.1.0"
description = "Digitale Gesamtausgabe der Werke Karl Gutzkows"
authors = ["Mark Hall <mark.hall@work.room3b.eu>"]

[tool.poetry.dependencies]
python = "^3.7"
pelican = "^4.2.0"
lxml = "^4.5.0"
click = "^7.1.1"
GitPython = "^3.1.1"
requests = "^2.23.0"
pelican-page-hierarchy = {git = "https://github.com/scmmmh/pelican-page-hierarchy.git"}
pelican-page-order = {git = "https://github.com/scmmmh/pelican-page-order.git"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
