# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Gutzkow Digitale Gesamtausgabe
author: Gutzkow Projekt
logo: _static/gutzkow-head.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    html_theme: pydata_sphinx_theme
    html_theme_options:
      secondary_sidebar_items:
        - page-toc.html
      favicons:
        - 'href': favicon.ico
      header_links_before_dropdown: 6
    language: de
  extra_extensions:
    - gutzkow_digitale_edition
    - sphinx_favicon

only_build_toc_files: true
