# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Gutzkow Digitale Gesamtausgabe
author: Gutzkow Projekt
copyright: 1996 - 2023
logo: _static/gutzkow-head.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    html_theme: pydata_sphinx_theme
    html_theme_options:
      secondary_sidebar_items:
        - page-toc.html
      header_links_before_dropdown: 6
      footer_start: []
      footer_end: []
    language: de
    favicons:
      - 'href': favicon.ico
    uEdition:
      tei:
        text_only_in_leaf_nodes: true
        sections:
          - title: Haupttext
            content: /tei:TEI/tei:text/tei:body/*
          - title: Apparat
            content: /tei:TEI/tei:text/tei:interpGrp[@type="global"]/*
          - title: Stellenerläuterungen
            content: /tei:TEI/tei:text/tei:body/tei:interp
            mappings:
              - selector:
                  tag: tei:interp
                tag: aside
                attributes:
                  - attr: id
                    action: delete
                  - attr: type
                    action: set
                    value: esv-list-item
          - title: Metadaten
            type: fields
            fields:
              - title: Bibliographischer Nachweis
                content: /tei:TEI/tei:teiHeader/tei:sourceDesc/tei:bibl/text()
              - title: Herausgeber und Herausgeberinnen
                type: list
                content: /tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:respStmt[tei:resp/text() = 'Herausgeber' or tei:resp/text() = 'Herausgeberin']/tei:name/text()
              - title: Fassung
                content: (/tei:TEI/tei:teiHeader/tei:revisionDesc/tei:change/text())[last()]
        mappings:
          - selector:
              tag: tei:head
              attributes:
                attr: type
                value: level-1
            tag: h1
          - selector:
              tag: tei:head
              attributes:
                attr: type
                value: level-2
            tag: h2
          - selector:
              tag: tei:head
              attributes:
                attr: type
                value: level-3
            tag: h3
          - selector:
              tag: tei:head
              attributes:
                attr: type
                value: level-4
            tag: h4
          - selector: tei:interp
            tag: aside
          - selector: tei:note
            tag: aside
          - selector: tei:seg
            tag:
          - selector:
              tag: tei:hi
              attributes:
                attr: style
                value: sup
            tag: sup
          - selector:
              tag: tei:pb
            tag: span
            text:
              action: from-attribute
              attr: 'n'
  extra_extensions:
    - uedition
    - sphinx_favicon

only_build_toc_files: true
