# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Gutzkow Digitale Gesamtausgabe
author: Gutzkow Projekt
logo: _static/gutzkow-head.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    html_theme: pydata_sphinx_theme
    html_theme_options:
      secondary_sidebar_items:
        - page-toc.html
      favicons:
        - 'href': favicon.ico
      header_links_before_dropdown: 6
    language: de
    uEdition:
      tei:
        text_only_in_leaf_nodes: true
        sections:
          - title: Haupttext
            content: /tei:TEI/tei:text/tei:body
          - title: Apparat
            content: /tei:TEI/tei:text/tei:interpGrp[@type="global"]
          - title: Stellenerläuterungen
            content: /tei:TEI/tei:text/tei:body/tei:interp
            mappings:
              - selector:
                  tag: tei:interp
                tag: aside
                attributes:
                  - attr: id
                    action: delete
                  - attr: type
                    action: set
                    value: esv-list-item
        mappings:
          - selector:
              tag: tei:head
              attributes:
                attr: type
                value: level-1
            tag: h1
          - selector:
              tag: tei:head
              attributes:
                attr: type
                value: level-2
            tag: h2
          - selector:
              tag: tei:head
              attributes:
                attr: type
                value: level-3
            tag: h3
          - selector:
              tag: tei:head
              attributes:
                attr: type
                value: level-4
            tag: h4
          - selector: tei:interp
            tag: aside
          - selector: tei:note
            tag: aside
          - selector: tei:seg
            tag:
          - selector:
              tag: tei:hi
              attributes:
                attr: style
                value: sup
            tag: sup
          - selector:
              tag: tei:pb
            tag: span
            text:
              action: from-attribute
              attr: 'n'
  extra_extensions:
    - gutzkow_digitale_edition
    - sphinx_favicon

only_build_toc_files: true
